//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jpmobapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesman
    {
        public Salesman()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int WarehouseId { get; set; }
    
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
